version: '2'
services:
  api:
    build: backend/
    command: gunicorn -w 4 main:app -w 2 --threads 2 -b 0.0.0.0:5000

    ports:
      - "8000:5000"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=logan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=example