name: Development Workflow
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test_Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          echo "PYTHON VERSION IS $(python --version)"
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Run Unit tests
        run: |
          # To extract percentage: https://unix.stackexchange.com/questions/690810/using-sed-to-parse-score
          COVERAGE=$(pytest --verbose --doctest-modules --color=yes --cov=main --cov-report=term | grep TOTAL | sed 's/.*[[:blank:]]//')
          echo "overall test coverage is $COVERAGE"
          #if [[ $COVERAGE < 2 ]] then echo "yes"; else echo "no"; fi
          COVERAGE_REMOVE_PERCENT=$(echo $COVERAGE | sed 's/\%//g')
          if [[ $COVERAGE_REMOVE_PERCENT -lt 75 ]]
          then
            echo "COVERAGE IS BELOW THRESHOLD";
            exit 1
          else 
            echo "COVERAGE IS ABOVE THRESHOLD, CONTINUING"; 
          fi